### PR TITLE
I have added the file for slider

### PR DESCRIPTION
**Pull request by shubhig226**

### CODE REVIEW

**Comment by uday03meh** [comment]
Hi, the [Deploy Preview](https://deploy-preview-7--uday03meh-password-generator.netlify.app/slider) is showing a blank page, if this is working in your local machine, can you share a screenshot or a video maybe?

I think this is because you haven't connected slider.html, slider.css and slider.js files to the index.html file.

image

**Comment by shubhig226** [comment]
Yeah maybe because of that, lemme do one change in the colour scheme and update it

**Comment by uday03meh** [comment]
It's still showing the blank screen :(
Maybe create another branch, let me merge it and then see if there are any changes.

**Comment by shubhig226** [comment]
https://user-images.githubusercontent.com/71431672/196780890-86ef5f94-16df-4d63-94c6-2977c2c00854.mp4

**Comment by shubhig226** [comment]
Lemme link it to the index file

**Comment by shubhig226** [comment]
Please check

**Comment by uday03meh** [comment]
I cloned your forked repo and this is what it's showing, I think the problem is with connecting the slider files with the main project.

image

**Comment by shubhig226** [comment]
Please check now.

**Comment by uday03meh** [comment]
Still no change :(

image

**Comment by shubhig226** [comment]
Idk y but I had added the file too in the index :(

**Comment by uday03meh** [comment]
Maybe you can work on some other issue or raise a new one, can I close this PR and assign this one to someone else?

**Comment by shubhig226** [comment]
Okay :(

**Comment by uday03meh** [comment]
Thank you for trying though!

**Pull request closed without merging**
