### PR TITLE
Fix Checkbox Selection bug

### PR DESCRIPTION
**Pull request by sshsrn**
Signed-off-by: SRIHARI S <sshsrn@gmail.com>

### CODE REVIEW

**Comment by sshsrn** [comment]
fixes #9

**Comment by sshsrn** [comment]
I am also adding a screen recording for your reference.

https://user-images.githubusercontent.com/62781914/197324481-6701fefc-e77c-44f9-980c-dad8872213ae.mp4

@uday03meh Kindly check!

**Comment by uday03meh** [comment]
Hi, I think when no checkboxes are selected and Generate is clicked, password field should get blank, Can please you add this in this PR?

**Comment by sshsrn** [comment]
I have fixed it now. Kindly check! @uday03meh

**Comment by uday03meh** [comment]
Perfect. Merging this
Thanks for your contributing!

**Pull request merged**
